- name: Configure server
  hosts: all
  remote_user: "{{ user }}"

- import_playbook: update-packages.yml
- import_playbook: harden-server.yml
- import_playbook: setup-tailscale.yml
- import_playbook: setup-postgres.yml
- import_playbook: setup-caddy.yml
