- name: Deploy application
  hosts: production
  become: true
  remote_user: "{{ user }}"

  vars:
    caddy_config_path: "/etc/caddy/Caddyfile"
    app_service_file: "/etc/systemd/system/{{ project_name }}.service"
    app_tarball: "{{ tarballs_dir }}/{{ project_name }}-{{ vsn_next }}.tar.gz"

  pre_tasks:
    - name: Check out main branch
      command:
        cmd: "git checkout main"
        chdir: "{{ repo_dir }}"
      delegate_to: localhost
      register: checkout_output
      changed_when: checkout_output.rc != 0

    - name: Check for uncommitted changes in git repo
      command:
        cmd: "git --git-dir={{ repo_dir }}/.git --work-tree={{ repo_dir }} status --porcelain"
        chdir: "{{ repo_dir }}"
      delegate_to: localhost
      register: git_status_output
      changed_when: false

    - name: Fail if there are uncommitted changes
      fail:
        msg: "There are uncommitted changes in the repository. Please commit them before proceeding."
      when: git_status_output.stdout != ""

    - name: Get next app version number
      shell:
        cmd: "grep -Po '(?<=version: \")[^\"]+' {{ repo_dir }}/mix.exs"
      register: vsn_next
      delegate_to: localhost
      changed_when: false

    - set_fact:
        vsn_next: "{{ vsn_next.stdout }}"

    - name: Get live app version number
      shell: |
        if [ -f '{{ app_dir }}/releases/start_erl.data' ]; then
          cut -d' ' -f2 '{{ app_dir }}/releases/start_erl.data'
        else
          echo ""
        fi
      register: vsn_live
      changed_when: false

    - set_fact:
        vsn_live: "{{ vsn_live.stdout }}"

    - name: Fail if the versions match
      fail:
        msg: "The live version ({{ vsn_live }}) matches the next version ({{ vsn_next }}). Deployment should not proceed."
      when: vsn_next == vsn_live

    - name: Ensure Caddy is started
      service:
        name: caddy
        state: started

  tasks:
    - name: Create maintenance directory
      file:
        path: "{{ maintenance_dir }}"
        state: directory

    - name: Create tarballs directory
      file:
        path: "{{ tarballs_dir }}"
        state: directory

    - name: Copy index.html
      template:
        src: templates/maintenance/index.html.j2
        dest: "{{ maintenance_dir }}/index.html"

    - name: Copy Caddyfile
      template:
        src: templates/Caddyfile.j2
        dest: "{{ caddy_config_path }}"
      register: caddyfile

    - name: Reload Caddy
      service:
        name: caddy
        state: reloaded
      when: caddyfile.changed

    - name: Copy unit file
      template:
        src: templates/app.service.j2
        dest: "{{ app_service_file }}"
      register: unit_file

    - name: Reload systemd daemon
      command: systemctl daemon-reload
      when: unit_file.changed

    - name: Run mix release
      shell: |
        cd {{ repo_dir }} && \
        mix deps.get --only prod && \
        MIX_ENV=prod mix do compile, assets.deploy, release
      become_user: "{{ user }}"
      delegate_to: localhost
      args:
        creates: "{{ repo_dir }}/_build/prod/{{ project_name }}-{{ vsn_next }}.tar.gz"

    - name: Copy app tarball to server
      copy:
        src: "{{ repo_dir }}/_build/prod/{{ project_name }}-{{ vsn_next }}.tar.gz"
        dest: "{{ app_tarball }}"

    - name: Create temporary app directory
      file:
        path: "{{ app_dir_tmp }}"
        state: directory

    - name: Extract the release to temporary app directory
      unarchive:
        src: "{{ app_tarball }}"
        dest: "{{ app_dir_tmp }}"
        remote_src: true

    - name: Copy env file
      template:
        src: templates/.env.j2
        dest: "{{ app_dir_tmp }}/.env"

    - name: Wait for port to close active connections
      wait_for:
        host: 0.0.0.0
        port: "{{ port }}"
        state: drained

    # Downtime starts here!
    - name: Stop app service
      service:
        name: "{{ project_name }}"
        state: stopped

    - name: Remove app directory
      file:
        path: "{{ app_dir }}"
        state: absent

    - name: Create app directory
      command:
        cmd: mv {{ app_dir_tmp }} {{ app_dir }}
      args:
        creates: "{{ app_dir }}"

    - name: Perform database migrations
      shell:
        cmd: "env $(grep -v '^#' {{ app_dir }}/.env | xargs) {{ app_dir }}/bin/migrate"
      register: migration_result
      changed_when: "'[info] Migrations already up' not in migration_result.stdout"

    - name: Start app service
      service:
        name: "{{ project_name }}"
        daemon_reload: true
        state: started

    - name: Check app is running
      wait_for:
        port: "{{ port }}"
        delay: 5
        timeout: 15
