- name: Setup Caddy
  hosts: production
  become: true
  remote_user: "{{ user }}"

  tasks:
    - name: Add repo
      community.general.copr:
        name: '@caddy/caddy'
        state: enabled

    - name: Install Caddy
      apt:
        update_cache: yes
        name: caddy
        state: present

    - name: Start and enable Caddy
      service:
        name: caddy
        state: started
        enabled: true
