- name: Setup Postgres
  hosts: production
  become: true
  remote_user: "{{ user }}"

  pre_tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - postgresql
        - postgresql-contrib
        - python3-psycopg2
        - acl

  tasks:
    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data

    # - name: "Initialize PostgreSQL"
    #   shell: "postgresql-setup initdb"
    #   when: not postgres_data.stat.exists

    - name: "Start and enable services"
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items:
        - postgresql

    - name: "Create app database"
      postgresql_db:
        state: present
        name: "{{ db_name }}"
      become: true
      become_user: postgres

    - name: "Create db user"
      postgresql_user:
        state: present
        name: "{{ db_user }}"
        password: "{{ db_password }}"
      become: true
      become_user: postgres

    # GRANT/REVOKE privs ON type objs TO/FROM roles
    - name: "Grant db user access to app db"
      postgresql_privs:
        database: "{{ db_name }}"
        privs: all
        type: database
        role: "{{ db_user }}"
        grant_option: false
      become: true
      become_user: postgres

    - name: "Grant db user access to public schema"
      postgresql_privs:
        database: "{{ db_name }}"
        privs: all
        type: schema
        obj: public
        role: "{{ db_user }}"
        grant_option: false
      become: true
      become_user: postgres

    - name: "Allow md5 connection for the db user"
      postgresql_pg_hba:
        dest: /etc/postgresql/14/main/pg_hba.conf
        contype: host
        databases: all
        method: md5
        users: "{{ db_user }}"
        create: true
      become: true
      become_user: postgres
      notify: Restart postgresql

  handlers:
    - name: Restart postgresql
      systemd:
        name: postgresql
        state: restarted
