- name: Setup ZSH and Oh My Zsh
  hosts: production
  remote_user: "{{ user }}"
  become: true
  # vars file for oh_my_zsh
  vars:
    powerlinefonts: powerline-fonts
    fdfind: fd-find
    dustversion: v0.8.3
    exaversion: v0.10.1
    zoxideversion: 0.9.1
    procsversion: v0.13.3
    with_starship: true
    copy_dot_files: true
  tasks:
    # tasks file for oh_my_zsh
    - name: Install Git
      become: true
      ansible.builtin.package:
        state: present
        name: git

    - name: Install ZSH
      become: true
      ansible.builtin.package:
        name: zsh
        state: present

        # Required for the Ubuntu repository (see below)
    - name: Install GPG and Wget in Ubuntu
      become: true
      ansible.builtin.package:
        state: present
        name:
          - gpg
          - wget
      when: ansible_os_family == 'Debian'

    - name: Override powerline fonts package name for Debian.
      ansible.builtin.set_fact:
        powerlinefonts: fonts-powerline
      when: ansible_os_family == 'Debian'

    - name: Install Powerline fonts
      become: true
      ansible.builtin.package:
        state: present
        name: "{{ powerlinefonts }}"

    # unzip is useful for extracting zips
    - name: Install unzip
      become: true
      ansible.builtin.package:
        state: present
        name: unzip

    # - name: Install Oh My Zsh # noqa: latest
    #   ansible.builtin.git:
    #     repo: https://github.com/ohmyzsh/ohmyzsh.git
    #     dest: "/home/{{ user }}/.oh-my-zsh"
    #     depth: 1

    - name: Download oh my zsh install script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: "/home/{{ user }}"
        mode: "0755"

    - name: Install oh-my-zsh (non-interactive)
      ansible.builtin.shell: "sh /home/{{ user }}/install.sh --unattended"
      become: yes
      become_user: "{{ user }}"

    - name: Install zsh-autosuggestions plugin # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: "/home/{{ user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
        depth: 1

    - name: Install zsh-completions plugin # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-completions
        dest: "/home/{{ user }}/.oh-my-zsh/custom/plugins/zsh-completions"
        depth: 1

    - name: Install zsh-syntax-highlighting plugin # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: "/home/{{ user }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
        depth: 1

    - name: Install autoupdate-zsh-plugin # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/TamCore/autoupdate-oh-my-zsh-plugins
        dest: "/home/{{ user }}/.oh-my-zsh/custom/plugins/autoupdate"
        depth: 1

    - name: Change user shell to zsh
      become: true
      ansible.builtin.user:
        name: "{{ user }}"
        shell: /bin/zsh
