- name: test
  hosts: production
  become: true
  remote_user: "{{ user }}"

  vars:
    caddy_config_path: "/etc/caddy/Caddyfile"
    app_service_file: "/etc/systemd/system/{{ project_name }}.service"
    app_tarball: "{{ tarballs_dir }}/{{ project_name }}-{{ vsn_next }}.tar.gz"
    hex_petal_auth_key: "{{ vault_hex_petal_auth_key }}"

  tasks:
    - name: Add custom Hex repository
      command: >
        mix hex.repo add petal https://petal.build/repo \
        --fetch-public-key SHA256:6Ff7LeQCh4464psGV3w4a8WxReEwRl+xWmgtuHdHsjs \
        --auth-key "{{ hex_petal_auth_key }}"
      when: hex_petal_auth_key is defined
