- name: test
  hosts: production
  become: true
  remote_user: "{{ user }}"

  vars:
    caddy_config_path: "/etc/caddy/Caddyfile"
    app_service_file: "/etc/systemd/system/{{ project_name }}.service"
    app_tarball: "{{ tarballs_dir }}/{{ project_name }}-{{ vsn_next }}.tar.gz"
    hex_petal_auth_key: "{{ vault_hex_petal_auth_key }}"

  tasks:
    - name: Copy env file
      template:
        src: templates/.env.j2
        dest: "{{ app_dir }}/.env"
