- name: Update packages
  hosts: production
  become: true
  remote_user: "{{ user }}"

  tasks:
    - name: Update all packages
      apt:
        upgrade: "yes"
        update_cache: "yes"
        autoremove: "yes"

    - name: Set system-wide timezone to Europe/Berlin
      ansible.builtin.timezone:
        name: Europe/Berlin
