- name: Update packages
  hosts: all
  become: true
  remote_user: "{{ user }}"

  tasks:
    - name: Update all packages
      apt:
        upgrade: "yes"
        update_cache: "yes"
        autoremove: "yes"
